<!DOCTYPE html>
<html>
<body>
    <footer>
        <p>&copy; 2025 ALIMSON Tech.</p>
        <p><a href="https://limuzuu.atlassian.net/jira/software/projects/AL/boards/34?atlOrigin=eyJpIjoiYTlkZmQ2Nzk1ODhlNDI5OThjMWMzYjMzNTk4ODFlY2MiLCJwIjoiaiJ9" target="_blank">Jira link</a>  </p>
        <p><a href="https://github.com/106213011/project1.git" target="_blank">GitHub Link</a></p>
    </footer>
</body>
</html>