<!DOCTYPE html>
<html>
<body>
    <nav class="navbar">
        <a href="index.html" class="active">Home</a> 
        <a href="jobs.html">Job Openings</a> 
        <a href="apply.html" >Job Application</a> 
        <a href="about.html" >About us</a>
        <div class="contact">
            <a href="#">Contact</a>
            <ul class="submenu">
                <li><a href="mailto:info@alimson.com">Email Us</a></li>
                <li><a href="tel:+60123456789">Call Us</a></li>
                <li><a href="contact.html">Contact Form</a></li>
            </ul>
        </div>
    </nav>
</body>
</html>